#!/usr/bin/env python3
"""Internal descriptors for extension-owned fragment loading."""
from __future__ import annotations

from .descriptors.core import (
    FragmentDescriptor,
    FragmentFieldDescriptor,
    load_fragment_payload,
)
from .descriptors.governance import (
    DISPATCH_OPERATIONS_DESCRIPTOR,
    DOCS_REGISTRY_DESCRIPTOR,
    DOCUMENTATION_CLOSURE_RULES_DESCRIPTOR,
    FULL_TEST_GROUP_REGISTRY_DESCRIPTOR,
    PATH_ENTRYPOINTS_DESCRIPTOR,
    RECOVERY_OPERATIONS_DESCRIPTOR,
    ROUTER_ROUTE_DESCRIPTOR,
    SETUP_FAILURES_DESCRIPTOR,
)
from .descriptors.registry import (
    AGENT_CLI_SURFACE_DESCRIPTOR,
    DIAGNOSTIC_SURFACE_DESCRIPTOR,
    OBJECT_FAMILIES_DESCRIPTOR,
    RUNTIME_CONTRACT_DESCRIPTOR,
    RUNTIME_SOURCE_STRATEGY_DESCRIPTOR,
)
from .descriptors.runtime import (
    DEPLOY_ENV_SCHEMA_DESCRIPTOR,
    GATEWAY_EXEC_APPROVALS_DESCRIPTOR,
    GATEWAY_READONLY_MANIFEST_DESCRIPTOR,
    RUNTIME_PATHS_DESCRIPTOR,
    RUNTIME_SERVICE_REGISTRY_DESCRIPTOR,
    TESTING_MANIFEST_DESCRIPTOR,
)


__all__ = [
    'AGENT_CLI_SURFACE_DESCRIPTOR',
    'DEPLOY_ENV_SCHEMA_DESCRIPTOR',
    'DIAGNOSTIC_SURFACE_DESCRIPTOR',
    'DISPATCH_OPERATIONS_DESCRIPTOR',
    'DOCS_REGISTRY_DESCRIPTOR',
    'DOCUMENTATION_CLOSURE_RULES_DESCRIPTOR',
    'FragmentDescriptor',
    'FragmentFieldDescriptor',
    'FULL_TEST_GROUP_REGISTRY_DESCRIPTOR',
    'GATEWAY_EXEC_APPROVALS_DESCRIPTOR',
    'GATEWAY_READONLY_MANIFEST_DESCRIPTOR',
    'OBJECT_FAMILIES_DESCRIPTOR',
    'PATH_ENTRYPOINTS_DESCRIPTOR',
    'RECOVERY_OPERATIONS_DESCRIPTOR',
    'ROUTER_ROUTE_DESCRIPTOR',
    'RUNTIME_CONTRACT_DESCRIPTOR',
    'RUNTIME_PATHS_DESCRIPTOR',
    'RUNTIME_SERVICE_REGISTRY_DESCRIPTOR',
    'RUNTIME_SOURCE_STRATEGY_DESCRIPTOR',
    'SETUP_FAILURES_DESCRIPTOR',
    'TESTING_MANIFEST_DESCRIPTOR',
    'load_fragment_payload',
]
